### ISSUE TITLE
asset/render.so: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by Algabri** [1996scarlet/Dense-Head-Pose-Estimation#11]
It worked well with:
$ `python3 demo_video.py -m pose -f ./re.mp4`
$` python3 demo_video.py -m sparse -f ./re.mp4`
$ `python3 demo_video.py -m dense -f ./re.mp4`

but with `mesh` not as you see here:

$` python3 demo_video.py -m mesh -f ./re.mp4 `
2022-12-05 17:03:03.713207: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "demo_video.py", line 55, in <module>
    main(args)
  File "demo_video.py", line 21, in main
    color = service.TrianglesMeshRender("asset/render.so", "asset/triangles.npy")
  File "/home/redhwan/2/HPE/tensorflow/Dense-Head-Pose-Estimation-main/service/CtypesMeshRender.py", line 17, in __init__
    self._clibs = ctypes.CDLL(clibs)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: asset/render.so: cannot open shared object file: No such file or directory

**Comment by 1996scarlet** [comment]
please check the [render-for-dense-face](https://github.com/1996scarlet/Dense-Head-Pose-Estimation#render-for-dense-face) section
