### ISSUE TITLE
there is no asset/render.so

### ISSUE THREAD

**Issue by hitxuhao** [1996scarlet/Dense-Head-Pose-Estimation#3]
Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "demo_video.py", line 53, in <module>
    main(args)
  File "demo_video.py", line 18, in main
    color = service.TrianglesMeshRender("asset/render.so",
  File "/home/xuhao/workspace/Dense-Head-Pose-Estimation-main/service/CtypesMeshRender.py", line 17, in __init__
    self._clibs = ctypes.CDLL(clibs)

**Comment by hitxuhao** [comment]
forgot to build build_render.sh
